name = "Brevity"
license = "MIT"
licenselink = "https://github.com/eweix/brevity/blob/master/LICENSE"
description = "Fast Hugo theme with sidebar."
homepage = "https://github.com/eweix/brevity/"
tags = ["blog", "plain"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "eweix"
  homepage = "https://github.com/eweix"
