name = "Brevity"
license = "MIT"
licenselink = "https://github.com/eweix/brevity/blob/master/LICENSE"
description = "Responsive hugo theme with dark mode and inline css."
homepage = "https://github.com/eweix/brevity/"
tags = ["blog", "plain", "responsive"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "eweix"
  homepage = "https://github.com/eweix"

# set sections to publish in RSS feed
mainSections = ['posts']

[menus]
[[menus.header]]
  name = 'Home'
  pageref = '/'
  weight = 1
[[menus.header]] 
  name = 'Posts'
  pageref = '/posts/'
  weight = 2
[[menus.footer]]
  name    = 'RSS'
  pageref = '/index.xml'
  weight  = 1

[params.csp]
  childsrc    = ["'self'"]  # configure behavior for web workers, nested scripts
  fontsrc     = ["'self'"]  # where fonts can be loaded from
  formaction  = ["'self'"]  # where form data can be submitted
  framesrc    = ["'self'"]  # domains that can serve iframe tags
  imgsrc      = ["'self'"]  # configure image sources
  objectsrc   = ["'none'"]  # configure plugins
  stylesrc    = ["'self'"]  # configure stylesheets
  scriptsrc   = ["'self'"]  # configure js behavior